@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

LAYOUT_WITH_LEGEND()

title Уровень 2. Диаграмма контейнеров

Person(Эколог, "Эколог организации")

Container_Boundary(1сОТКО, "1с: Отчетность ТКО"){

Container_Boundary(ОТКО, "Отчетность ТКО"){
    Component(ДокументТКО, "Документ ввода поступивших ТКО", "", "")
    Component(Отчеты, "Отчеты за период", "", "")
    Component(Справочники, "Справочники", "", "")
    Component(Регистры, "Регистры накоплений", "", "")
    Component(Перечисления, "Системные перечисления", "", "")
    Rel(ДокументТКО, Регистры, "Сохранение данных")
    Rel(Регистры, Отчеты, "Формирование отчетов")
    Rel(Отчеты, Эколог, "Сохранение отчетов в нужном формате")
    Rel(Справочники, ДокументТКО, "Справочная информация")
    Rel(Перечисления, ДокументТКО, "Справочная информация")
}
Container_Boundary(БСП, "БСП"){
    Component(Пользователи, "Подсистема пользователей")
    Component(БазовыйФункционал, "Подсистема базавых функция")
    Rel(Эколог, Пользователи, "Идентификация")
    Rel(Пользователи, ДокументТКО, "Ввод данных")
    Rel(Пользователи, Справочники, "Ввод данных")
    Rel(БазовыйФункционал, ОТКО, "Использование общих функция")
}

}





@enduml