@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

LAYOUT_WITH_LEGEND()

title УУровень 3. Диаграмма компонентов

Container_Boundary(ОТКО, "Отчетность ТКО"){
    Container_Boundary(Справочники, "Справочники"){
        Component(КлассификаторОтходов, "Классификатор отходов", "", "")
        Component(Контрагенты, "Контрагенты", "", "")
        Component(Организации, "Организации", "", "")
        Component(Договоры, "Догоыворы", "", "")
    }
    Container_Boundary(Документы, "Документы"){
        Component(РегистрацияОтходов, "РегистрацияОтходов", "", "")
        Rel(Договоры, РегистрацияОтходов, "")
        Rel(Организации, РегистрацияОтходов, "")
        Rel(Контрагенты, РегистрацияОтходов, "")
        Rel(КлассификаторОтходов, РегистрацияОтходов, "")
    }
    Container_Boundary(Регистры, "Регистры накоплений"){
        Component(ОтходыПолученные, "Отходы полученные", "", "")
        Component(ОтходыПоЦелиПередачи, "Отходы по цели передачи", "", "")
        Component(ОтходыПоДействию, "Отходы по действию", "", "")
        Rel(РегистрацияОтходов, ОтходыПолученные, "")
        Rel(РегистрацияОтходов, ОтходыПоЦелиПередачи, "")
        Rel(РегистрацияОтходов, ОтходыПоДействию, "")
    }
    Container_Boundary(Отчеты, "Отчеты"){
        Component(БольшойФайл, "Большой файл", "", "Отчет повторяет эксель файл с которым работали ранее")
        Component(ОтходыПоПериоду, "Отходы по периоду", "", "")
        Rel(ОтходыПолученные, ОтходыПоПериоду, "")
        Rel(ОтходыПоЦелиПередачи, ОтходыПоПериоду, "")
        Rel(ОтходыПоДействию, ОтходыПоПериоду, "")
        Rel(ОтходыПолученные, БольшойФайл, "")
    }
    Container_Boundary(Перечисления, "Перечисления"){
        Component(СпособПолучения, "Способ получения отхода", "", "")
        Component(ДействиеСОтходом, "Действие с отходом", "", "")
        Component(ЦельПередачи, "Цель передачи отхода", "", "")
        Rel(СпособПолучения, РегистрацияОтходов, "")
        Rel(ДействиеСОтходом, РегистрацияОтходов, "")
        Rel(ЦельПередачи, РегистрацияОтходов, "")
    }

}



@enduml